obstacle_range: 15.0
raytrace_range: 20.0
#footprint: [[0.5,0.4],[0.5,-0.4],[-0.5,-0.4],[-0.5,0.4]]
footprint: [[0.435, 0.69], [0.435, -0.68], [-0.435, -0.68],[-0.435,0.68]]  # if the robot is not
inflation_radius: 1.5
cost_scaling_factor: 2.0
max_obstacle_height: 2.0
min_obstacle_height: 0.2
observation_sources: scan
scan: {sensor_frame: /velodyne, data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: true, expected_update_rate: 5.0}
