global_costmap:
   global_frame: /odom
   robot_base_frame: /base_link
   update_frequency: 5.0     #1.0
   publish_frequency: 5.0     #1.0
   static_map: true
   rolling_window: false
   resolution: 0.2
   transform_tolerance: 2.0
   map_type: costmap
   width: 200.0
   height: 200.0
   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}

